Document: mingw-w64-libcroco
Title: Debian mingw-w64-libcroco Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-libcroco is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-libcroco/mingw-w64-libcroco.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-libcroco/mingw-w64-libcroco.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-libcroco/mingw-w64-libcroco.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-libcroco/html/index.html
Files: /usr/share/doc/mingw-w64-libcroco/html/*.html
